
services:
  db:
    image: postgres:16.4
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 1s
  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      AMQ_USER: quarkus
      AMQ_PASSWORD: quarkus
      AMQ_PROTOCOLS: "CORE, AMQP"
      AMQ_EXTRA_ARGS: "--no-autotune"

  app:
    image: cargotracker:latest
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_ARTEMIS_URL=tcp://artemis:61616
      - QUARKUS_ARTEMIS_USERNAME=quarkus
      - QUARKUS_ARTEMIS_PASSWORD=quarkus
    depends_on:
      db:
        condition: service_healthy
      artemis:
        condition: service_started
    ports:
      - "8080:8080"
